# Generated by Django 4.1 on 2022-09-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAX', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pax',
            old_name='CIU',
            new_name='code',
        ),
    ]
