# Generated by Django 4.1 on 2022-10-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_level5"),
        ("PAX", "0002_rename_ciu_pax_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pax",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.region",
            ),
        ),
        migrations.AddField(
            model_name="pax",
            name="responsable",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
