# Generated by Django 4.1 on 2022-10-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAX", "0005_alter_objectif_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="pax",
            name="adresse",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
