# Generated by Django 4.1 on 2022-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAX", "0006_pax_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="pax",
            name="ciu",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
