# Generated by Django 4.1 on 2022-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAX", "0007_pax_ciu"),
    ]

    operations = [
        migrations.AddField(
            model_name="pax",
            name="date_inscription",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
