# Generated by Django 4.1 on 2022-11-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAX", "0009_pax_nouveau"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pax",
            name="nouveau",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
