# Generated by Django 4.1 on 2022-11-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAX", "0010_alter_pax_nouveau"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pax",
            name="date_inscription",
            field=models.DateField(blank=True, null=True),
        ),
    ]
