# Generated by Django 4.1 on 2022-12-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PAX", "0011_alter_pax_date_inscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="pax",
            name="serial_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
