# Generated by Django 4.1 on 2022-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=250, null=True)),
                ('datePub', models.DateField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
