# Generated by Django 4.1 on 2022-10-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0003_level5"),
        ("PAX", "0006_pax_adresse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("uid", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.CharField(blank=True, max_length=250, null=True)),
                ("parentid", models.CharField(blank=True, max_length=250, null=True)),
                ("hierarchylevel", models.IntegerField(blank=True, null=True)),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.commune",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.district",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collecte_WHP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_cible", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type_demande",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type_referent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("referent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "page_sensibilisation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_collecte", models.DateField(auto_now_add=True, null=True)),
                ("responsable", models.IntegerField(blank=True, null=True)),
                (
                    "pax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAX.pax",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.region",
                    ),
                ),
            ],
        ),
    ]
