# Generated by Django 4.1 on 2022-10-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WHP", "0002_cpf_adresse_cpf_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sexe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
