# Generated by Django 4.1 on 2022-09-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_csb"),
        ("VIH", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pe",
            name="code",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="pe",
            name="hierarchylevel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pe",
            name="parentid",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="pe",
            name="uid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="referent",
            name="csb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.csb",
            ),
        ),
        migrations.DeleteModel(name="Csb",),
    ]
