# Generated by Django 4.1 on 2022-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0004_dicmeva_ville"),
    ]

    operations = [
        migrations.AddField(
            model_name="sexe",
            name="value",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
