# Generated by Django 4.1 on 2022-10-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0005_sexe_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collecte",
            name="type_demande",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
