# Generated by Django 4.1 on 2022-10-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0006_alter_collecte_type_demande"),
    ]

    operations = [
        migrations.RemoveField(model_name="collecte", name="responsable",),
    ]
