# Generated by Django 4.1 on 2022-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0007_remove_collecte_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte",
            name="responsable",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
