# Generated by Django 4.1 on 2022-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0009_intrant_distribution_intrant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution_intrant",
            name="mois",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
