# Generated by Django 4.1 on 2022-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0010_alter_distribution_intrant_mois"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte",
            name="frequence",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
