# Generated by Django 4.1 on 2022-11-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIH", "0011_collecte_frequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution_intrant",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
