# Generated by Django 4.1 on 2022-10-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("PAX", "0005_alter_objectif_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collecte_ezaho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_collecte", models.DateField(auto_now_add=True, null=True)),
                (
                    "pax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PAX.pax",
                    ),
                ),
            ],
        ),
    ]
