# Generated by Django 4.1 on 2022-10-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ezaho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte_ezaho",
            name="referent",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
