# Generated by Django 4.1 on 2022-09-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CIU", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciu",
            name="uid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
