# Generated by Django 4.1 on 2022-10-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CIU", "0003_ciu_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciu",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
