# Generated by Django 4.1 on 2022-10-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CIU", "0004_alter_ciu_date_created"),
    ]

    operations = [
        migrations.RemoveField(model_name="ciu", name="is_used",),
    ]
