# Generated by Django 4.1 on 2022-10-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CIU", "0005_remove_ciu_is_used"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ciu", old_name="date_created", new_name="datetime",
        ),
    ]
